branches:
 # whitelist

  # blacklist
  except:
    - gh-pages

image: Visual Studio 2022
configuration: Release
platform: Any CPU

assembly_info:
  patch: false

install:
  - choco install gitversion.portable -pre -y
  
before_build:
- ps: gitversion /l console /output buildserver /updateAssemblyInfo
- cmd: nuget restore PA.Utilities.sln

build:
  project: PA.Utilities.sln			# path to Visual Studio solution or project
  publish_nuget: false				# package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     	# generate and publish NuGet symbol packages
  include_nuget_references: true	# add -IncludeReferencedProjects option while packaging NuGet artifacts
  verbosity: normal

test: off

artifacts:
- path: '**/PA.Utilities.*.nupkg'

deploy:
- provider: Environment
  name: NuGet
  on:
    branch: master
- provider: Environment
  name: github.com
  on:
    branch: master
